-- 코드를 입력하세요
SELECT DISTINCT CAR_ID, CAR_TYPE, FEE
FROM (
    SELECT A.CAR_ID, A.CAR_TYPE, FLOOR(A.DAILY_FEE * 30 * (1-D.DISCOUNT_RATE/100)) FEE
    FROM (
        SELECT C.CAR_ID, C.CAR_TYPE, C.DAILY_FEE
        FROM CAR_RENTAL_COMPANY_CAR C LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
        WHERE (C.CAR_TYPE = "세단" OR C.CAR_TYPE = "SUV")
            AND C.CAR_ID NOT IN (
                SELECT CAR_ID
                FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01' 
            )
        ) A
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
    ON A.CAR_TYPE = D.CAR_TYPE AND D.DURATION_TYPE = "30일 이상"
) B
WHERE FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC