-- 코드를 입력하세요
SELECT A.CATEGORY, A.PRICE AS MAX_PRICE, A.PRODUCT_NAME
FROM FOOD_PRODUCT A 
    JOIN (
        SELECT CATEGORY, MAX(PRICE) MAX_PRICE
        FROM FOOD_PRODUCT
        GROUP BY CATEGORY
        HAVING CATEGORY IN ('과자', '국', '김치', '식용유')
    ) SUB
    ON A.CATEGORY = SUB.CATEGORY AND A.PRICE = SUB.MAX_PRICE
ORDER BY MAX_PRICE DESC